ethereum_rpc = "https://rpc.hoodi.ethpandaops.io"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.fee_anomaly_trap]
path = "out/FeeAnomalyTrap.sol/FeeAnomalyTrap.json"
response_contract = "0xa09Ad0c9a400f99c95252acc241831bfb22c7c7F"
response_function = "respondCallback(uint256)"
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 10
private_trap = true
whitelist = ["0x9057f3EDB531f1d418D0F577Db7836d75ccC260A"]
